<a href="https://colab.research.google.com/github/Vicks-2019/Fliprobo/blob/master/Spam_Email_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# To detect if an email is spam or not..



In [16]:
import numpy as np # linear algebra
import pandas as pd 
import matplotlib.pyplot as plt
import re
import nltk
from nltk.corpus import stopwords
import string

In [17]:
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails (1).csv


In [18]:
# Read the csv file
df = pd.read_csv('emails.csv')
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [19]:
df.shape

(5728, 2)

In [20]:
#Checking for duplicates and removing them
df.drop_duplicates(inplace = True)

In [21]:
df.columns

Index(['text', 'spam'], dtype='object')

In [22]:
df.shape

(5695, 2)

In [23]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [26]:
#Download stopwords
nltk.download('stopwords')
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [36]:
#Data cleaning and preprocessing
df['text']=df['text'].map(lambda text: text[1:])
df['text'] = df['text'].map(lambda text:re.sub('[^a-zA-Z0-9]+', ' ',str(text))).apply(lambda x: (x.lower()).split())
ps = PorterStemmer()
corpus=df['text'].apply(lambda text_list:' '.join(list(map(lambda word:ps.stem(word),(list(filter(lambda text:text not in set(stopwords.words('english')),text_list)))))))


In [37]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500)
X = cv.fit_transform(corpus).toarray()

y=pd.get_dummies(df['spam'])
y=y.iloc[:,1].values


In [38]:
# Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [39]:
# Training model using Naive bayes classifier

from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

In [46]:
#print the prediction
y_pred = print(classifier.predict(X_train))

[0 0 0 ... 0 0 0]


In [47]:
#print the actual values
print(y_train)

[0 0 0 ... 0 0 0]


In [48]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train,pred))
print('Confusion Matrix: \n',confusion_matrix(y_train,pred))
print()
print('Accuracy:',accuracy_score(y_train,pred))

                        

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      3457
           1       0.94      0.98      0.96      1099

    accuracy                           0.98      4556
   macro avg       0.97      0.98      0.97      4556
weighted avg       0.98      0.98      0.98      4556

Confusion Matrix: 
 [[3386   71]
 [  23 1076]]

Accuracy: 0.979367866549605


In [49]:
#print the prediction
y_pred = print(classifier.predict(X_test))

#print the actual values
print(y_test)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
